# Generated by Django 5.2.5 on 2025-08-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w_server', '0002_artist_managed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
    ]
