# Generated by Django 5.2.5 on 2025-08-17 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_server', '0003_remove_artist_bio_remove_artist_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_server.genre'),
        ),
    ]
