# Generated by Django 5.2.5 on 2025-08-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_server', '0004_artist_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file_url',
            field=models.FileField(upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture_url',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
