# Generated by Django 5.2.5 on 2025-08-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_server', '0005_alter_song_audio_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='credits',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
