# Generated by Django 5.2.5 on 2025-08-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_server', '0006_song_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(null=True, related_name='songs', through='w_server.SongGenre', to='w_server.genre'),
        ),
    ]
