# Generated by Django 5.2.5 on 2025-08-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w_server', '0007_alter_song_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
    ]
