# Generated by Django 5.2.5 on 2025-08-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_server', '0008_remove_album_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_cover_upload',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
