# Generated by Django 5.2.5 on 2025-08-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w_server', '0009_song_song_cover_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_cover_upload',
        ),
    ]
