# Generated by Django 5.2.5 on 2025-08-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_server', '0010_remove_song_song_cover_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_cover_upload',
            field=models.ImageField(default='rtx', upload_to='images/'),
        ),
    ]
