# Generated by Django 5.2.5 on 2025-08-28 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_server', '0011_song_song_cover_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_art_url',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_art_upload',
            field=models.ImageField(default=datetime.datetime(2025, 8, 28, 12, 58, 11, 102487, tzinfo=datetime.timezone.utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
