# Generated by Django 5.2.5 on 2025-09-03 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_server', '0012_remove_album_cover_art_url_album_cover_art_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_art_upload',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
