# Generated by Django 5.2.5 on 2025-09-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_server', '0013_playlist_cover_art_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
